### ISSUE TITLE
 Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by bellafontes** [edasque/DynamoDBtoCSV#27]
I tried run "node dynamoDBtoCSV.js  --help" either  localhost or docker compose file. After running 
both sides the same error occurried (I checked all the dependencies before has installed).

web_1   | Error: Cannot find module 'commander'
web_1   |     at Function.Module._resolveFilename (module.js:485:15)
web_1   |     at Function.Module._load (module.js:437:25)
web_1   |     at Module.require (module.js:513:17)
web_1   |     at require (internal/module.js:11:18)
web_1   |     at Object.<anonymous> (/code/dynamoDBtoCSV.js:1:77)
web_1   |     at Module._compile (module.js:569:30)
web_1   |     at Object.Module._extensions..js (module.js:580:10)
web_1   |     at Module.load (module.js:503:32)
web_1   |     at tryModuleLoad (module.js:466:12)
web_1   |     at Function.Module._load (module.js:458:3)

**Comment by edasque** [comment]
Have you run ```npm install``` before running the app?

If so, can you run ```ls node_modules``` for me?
