### ISSUE TITLE
SynstaxError when running on ubuntu

### ISSUE THREAD

**Issue by MarcoPorracin** [edasque/DynamoDBtoCSV#40]
Im getting this error when running on ubuntu:

`/home/ubuntu/DynamoDBtoCSV/dynamoDBtoCSV.js:74
        console.log(Papa.unparse( { fields: [ ...headers ], data: unMarshalledArray } ));
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

Versions:
npm 3.5.2
node 4.2.6

**Comment by MarcoPorracin** [comment]
Just needed to update node.

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
